[project]
name="src",
version=0.0.1,
description="Vehicle insurance prediction project"
author=({"author":"haseeb","email":"haseebmanzoor1511@gmail.com"})



[tool.setuptools]
packages = {find={}}


[tool.setuptools.dynamic]
dependencies = {"file":"requirements.txt"}
o